# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "
      while ! nc -z db 5432; do
      echo 'Waiting for database...';
      sleep 2;
      done;
      echo 'Database is ready!';
      python scripts/seed_database.py;
      uvicorn main:app --host 0.0.0.0 --port 8000
      "

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

volumes:
  postgres_data:
